"""init schema

Revision ID: 1b0ea4219dd0
Revises:
Create Date: 2026-07-10 09:27:44.701137

"""

from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0ea4219dd0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Provider type: openai, anthropic, moonshot, minimax, zhipu'),
    sa.Column('key', sa.String(length=500), nullable=False, comment='API Key for the provider'),
    sa.Column('base_url', sa.String(length=500), nullable=False, comment='Base URL for the provider API'),
    sa.Column('models', sa.JSON(), nullable=False, comment='List of models available on this channel'),
    sa.Column('model_mapping', sa.JSON(), nullable=False, comment='Mapping from user-facing model names to provider model names'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Channel priority (higher = preferred)'),
    sa.Column('weight', sa.Integer(), nullable=False, comment='Weight for load balancing within same priority'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether the channel is enabled'),
    sa.Column('test_only', sa.Boolean(), nullable=False, comment='Whether channel is for testing only'),
    sa.Column('protocol', sa.String(length=20), nullable=False, comment='Protocol: openai or anthropic'),
    sa.Column('rpm_limit', sa.Integer(), nullable=True, comment='Requests per minute limit'),
    sa.Column('tpm_limit', sa.Integer(), nullable=True, comment='Tokens per minute limit'),
    sa.Column('extra', sa.JSON(), nullable=False, comment='Extra configuration'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_table('conversation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('protocol', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_records_channel_id'), 'conversation_records', ['channel_id'], unique=False)
    op.create_index(op.f('ix_conversation_records_conversation_id'), 'conversation_records', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_records_created_at'), 'conversation_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_records_id'), 'conversation_records', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_records_model'), 'conversation_records', ['model'], unique=False)
    op.create_index(op.f('ix_conversation_records_request_id'), 'conversation_records', ['request_id'], unique=False)
    op.create_index(op.f('ix_conversation_records_status'), 'conversation_records', ['status'], unique=False)
    op.create_index(op.f('ix_conversation_records_token_id'), 'conversation_records', ['token_id'], unique=False)
    op.create_index(op.f('ix_conversation_records_user_id'), 'conversation_records', ['user_id'], unique=False)
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('request_model', sa.String(length=100), nullable=False, comment='Original model name in request'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True, comment='Request latency in seconds'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_channel_id'), 'request_logs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_request_logs_created_at'), 'request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_logs_id'), 'request_logs', ['id'], unique=False)
    op.create_index(op.f('ix_request_logs_model'), 'request_logs', ['model'], unique=False)
    op.create_index(op.f('ix_request_logs_token_id'), 'request_logs', ['token_id'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('quota', sa.Integer(), nullable=True, comment='Token quota limit (tokens), null means unlimited'),
    sa.Column('used_quota', sa.Integer(), nullable=False, comment='Used quota in tokens'),
    sa.Column('group', sa.String(length=50), nullable=False, comment='User group for channel access control'),
    sa.Column('allowed_channels', sa.JSON(), nullable=True, comment='List of channel IDs this token can access, null means all'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.Column('expire_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='Total tokens consumed'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_index(op.f('ix_tokens_key'), 'tokens', ['key'], unique=True)
    op.create_index(op.f('ix_tokens_user_id'), 'tokens', ['user_id'], unique=False)
    op.create_table('usage_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('provider_model', sa.String(length=100), nullable=True),
    sa.Column('request_protocol', sa.String(length=50), nullable=False),
    sa.Column('provider_protocol', sa.String(length=50), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=False),
    sa.Column('input_audio_tokens', sa.Integer(), nullable=False),
    sa.Column('output_audio_tokens', sa.Integer(), nullable=False),
    sa.Column('usage_source', sa.String(length=30), nullable=False),
    sa.Column('input_cost', sa.Float(), nullable=False),
    sa.Column('output_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_ledger_channel_id'), 'usage_ledger', ['channel_id'], unique=False)
    op.create_index(op.f('ix_usage_ledger_conversation_id'), 'usage_ledger', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_usage_ledger_created_at'), 'usage_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_ledger_id'), 'usage_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_usage_ledger_model'), 'usage_ledger', ['model'], unique=False)
    op.create_index(op.f('ix_usage_ledger_request_id'), 'usage_ledger', ['request_id'], unique=False)
    op.create_index(op.f('ix_usage_ledger_status'), 'usage_ledger', ['status'], unique=False)
    op.create_index(op.f('ix_usage_ledger_token_id'), 'usage_ledger', ['token_id'], unique=False)
    op.create_index(op.f('ix_usage_ledger_user_id'), 'usage_ledger', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_ledger_user_id'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_token_id'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_status'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_request_id'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_model'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_id'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_created_at'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_conversation_id'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_channel_id'), table_name='usage_ledger')
    op.drop_table('usage_ledger')
    op.drop_index(op.f('ix_tokens_user_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_key'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_request_logs_token_id'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_model'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_id'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_created_at'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_channel_id'), table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index(op.f('ix_conversation_records_user_id'), table_name='conversation_records')
    op.drop_index(op.f('ix_conversation_records_token_id'), table_name='conversation_records')
    op.drop_index(op.f('ix_conversation_records_status'), table_name='conversation_records')
    op.drop_index(op.f('ix_conversation_records_request_id'), table_name='conversation_records')
    op.drop_index(op.f('ix_conversation_records_model'), table_name='conversation_records')
    op.drop_index(op.f('ix_conversation_records_id'), table_name='conversation_records')
    op.drop_index(op.f('ix_conversation_records_created_at'), table_name='conversation_records')
    op.drop_index(op.f('ix_conversation_records_conversation_id'), table_name='conversation_records')
    op.drop_index(op.f('ix_conversation_records_channel_id'), table_name='conversation_records')
    op.drop_table('conversation_records')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
