window.ROTOR_UI_CONFIG = {
  defaultLocale: "zh-CN",
  locales: {
    "zh-CN": {
      pageTitle: "Rotor 管理控制台",
      subtitle: "模型渠道、API Key、用量与请求日志",
      language: "English",
      overview: "接入信息",
      channels: "模型渠道",
      apiKeys: "API Key",
      usage: "用量统计",
      logs: "请求日志",
      gatewayTitle: "统一 API 入口",
      gatewayDescription: "使用 Rotor 创建的 API Key，即可通过以下兼容协议调用已接入的模型。",
      baseUrl: "服务地址",
      protocol: "协议",
      endpoint: "调用地址",
      refresh: "刷新",
      addChannel: "新增渠道",
      channelsDescription: "管理上游服务的 API Key、模型和分发规则。",
      createKey: "创建 API Key",
      keyDescription: "该 Key 用于客户端调用 Rotor 的统一 API，不是上游服务的 Key。",
      keyName: "Key 名称",
      userOptional: "用户标识（可选）",
      quotaOptional: "配额（可选）",
      allowedChannels: "允许的渠道 ID，逗号分隔（留空表示全部）",
      generateKey: "生成 Key",
      addChannelTitle: "新增模型渠道",
      addChannelDescription: "配置一个上游 API Key 及其可用模型。",
      close: "关闭",
      name: "名称",
      provider: "服务商",
      upstreamBaseUrl: "上游 Base URL",
      upstreamApiKey: "上游 API Key",
      priority: "优先级",
      weight: "权重",
      models: "模型列表",
      modelMapping: "模型映射 JSON",
      enabled: "启用",
      probeModels: "探测模型",
      saveChannel: "保存渠道",
      saving: "保存中...",
      copy: "复制",
      copied: "已复制",
      test: "测试",
      disable: "停用",
      enable: "启用",
      delete: "删除",
      resetUsage: "重置用量",
      unlimited: "不限",
      created: "创建成功",
      generated: "API Key 已生成并复制到剪贴板",
      confirmDeleteChannel: "确定删除渠道",
      confirmDeleteKey: "确定删除 API Key",
      reachable: "可访问",
      failed: "失败",
      foundModels: "个模型，耗时",
      requireProbeFields: "探测模型前请先填写上游 Base URL 和 API Key",
      columns: {
        name: "名称", provider: "服务商 / 协议", baseUrl: "上游地址", models: "模型",
        route: "分发", status: "状态", requests: "请求", actions: "操作",
        id: "ID", key: "API Key", user: "用户", quota: "配额", used: "已用",
        time: "时间", token: "Key", channel: "渠道", tokens: "Token 数",
        error: "错误", latency: "延迟",
      },
      metrics: ["请求数", "成功", "失败", "Token 总数", "输入 Token", "输出 Token", "费用", "平均延迟"],
    },
    en: {
      pageTitle: "Rotor Admin",
      subtitle: "Model channels, API keys, usage, and request logs",
      language: "中文",
      overview: "API Access",
      channels: "Channels",
      apiKeys: "API Keys",
      usage: "Usage",
      logs: "Logs",
      gatewayTitle: "Unified API Endpoints",
      gatewayDescription: "Use an API key created by Rotor to call all connected models through these compatible protocols.",
      baseUrl: "Base URL",
      protocol: "Protocol",
      endpoint: "Endpoint",
      refresh: "Refresh",
      addChannel: "Add Channel",
      channelsDescription: "Manage upstream API keys, models, and routing rules.",
      createKey: "Create API Key",
      keyDescription: "This key is used by clients to call Rotor, not by Rotor to call upstream providers.",
      keyName: "Key name",
      userOptional: "User ID (optional)",
      quotaOptional: "Quota (optional)",
      allowedChannels: "Allowed channel IDs, comma separated (blank means all)",
      generateKey: "Generate Key",
      addChannelTitle: "Add Model Channel",
      addChannelDescription: "Configure one upstream API key and its available models.",
      close: "Close",
      name: "Name",
      provider: "Provider",
      upstreamBaseUrl: "Upstream Base URL",
      upstreamApiKey: "Upstream API Key",
      priority: "Priority",
      weight: "Weight",
      models: "Models",
      modelMapping: "Model Mapping JSON",
      enabled: "Enabled",
      probeModels: "Probe Models",
      saveChannel: "Save Channel",
      saving: "Saving...",
      copy: "Copy",
      copied: "Copied",
      test: "Test",
      disable: "Disable",
      enable: "Enable",
      delete: "Delete",
      resetUsage: "Reset Usage",
      unlimited: "Unlimited",
      created: "created",
      generated: "API key generated and copied to clipboard",
      confirmDeleteChannel: "Delete channel",
      confirmDeleteKey: "Delete API key",
      reachable: "reachable",
      failed: "failed",
      foundModels: "models found in",
      requireProbeFields: "Enter the upstream Base URL and API key before probing models",
      columns: {
        name: "Name", provider: "Provider / Protocol", baseUrl: "Upstream URL", models: "Models",
        route: "Route", status: "Status", requests: "Requests", actions: "Actions",
        id: "ID", key: "API Key", user: "User", quota: "Quota", used: "Used",
        time: "Time", token: "Key", channel: "Channel", tokens: "Tokens",
        error: "Error", latency: "Latency",
      },
      metrics: ["Requests", "Success", "Failed", "Total Tokens", "Prompt Tokens", "Completion Tokens", "Cost", "Avg Latency"],
    },
  },
};
