window.ROTOR_UI_CONFIG = {
  defaultLocale: "zh-CN",
  locales: {
    "zh-CN": {
      pageTitle: "Rotor 管理控制台",
      subtitle: "模型渠道、API Key、用量与请求日志",
      language: "English",
      overview: "接入信息",
      channels: "模型渠道",
      apiKeys: "API Key",
      usage: "用量统计",
      logs: "请求日志",
      mindagentChat: "MindAgent 对话",
      conversations: "对话记录",
      newConversation: "新对话",
      deleteConversation: "删除对话",
      confirmDeleteConversation: "确定删除这条本地对话记录吗？",
      model: "模型",
      selectModel: "选择模型",
      selectModelFirst: "请先选择一个可用模型",
      noModelsAvailable: "暂无可用模型",
      agentReady: "已就绪",
      agentThinking: "正在思考…",
      mindagentUnavailable: "MindAgent 尚未安装",
      chatTokenUnavailable: "请先创建 Rotor API Key",
      chatServiceUnavailable: "聊天服务不可用",
      chatPlaceholder: "给 MindAgent 发送消息…",
      addAttachment: "添加内容",
      addPhoto: "添加照片",
      addPhotoHint: "JPG、PNG、GIF 或 WebP",
      addFile: "添加文件",
      addFileHint: "文本、代码、JSON 或 CSV",
      webSearch: "网页搜索",
      comingSoon: "即将支持",
      webSearchComingSoon: "网页搜索功能暂未实现",
      removeAttachment: "移除附件",
      tooManyAttachments: "一次最多添加 6 个附件",
      attachmentsTooLarge: "附件总大小不能超过 10 MB",
      imageTooLarge: "图片不能超过 5 MB",
      fileTooLarge: "文件不能超过 500 KB",
      unsupportedFileType: "当前仅支持文本、代码和结构化数据文件",
      fileReadFailed: "无法读取文件",
      defaultAttachmentPrompt: "请分析这些附件。",
      sendMessage: "发送消息",
      stopGenerating: "停止生成",
      chatHint: "Enter 发送，Shift + Enter 换行。AI 输出可能存在错误，请核对重要信息。",
      chatWelcome: "有什么可以帮你？",
      chatWelcomeDescription: "通过 Rotor 已配置的模型渠道，与 MindAgent 进行连续对话。",
      chatSuggestionOne: "介绍一下你能帮我完成什么",
      chatSuggestionTwo: "帮我梳理一个技术方案",
      chatSuggestionThree: "解释一段复杂概念",
      you: "你",
      chatFailed: "生成失败",
      emptyResponse: "模型没有返回内容。",
      generationStopped: "已停止生成。",
      streamUnavailable: "浏览器不支持流式响应",
      copyFailed: "复制失败",
      settings: "设置",
      settingsDescription: "配置 Rotor 的运行参数。",
      routingSettings: "路由设置",
      routingSettingsDescription: "控制多个渠道之间的选择方式和会话粘性。",
      routingStrategy: "路由策略",
      strategyPriorityWeighted: "优先级 + 权重分摊",
      strategyFallbackOrder: "固定主备顺序",
      strategyWeighted: "全局权重分摊",
      affinityEnabled: "启用会话亲和",
      affinityDescription: "分摊流量时让相同会话稳定使用同一渠道；固定主备策略不受此项影响。",
      settingsFile: "配置文件",
      saveSettings: "保存设置",
      settingsSaved: "设置已保存并立即生效",
      gatewayTitle: "统一 API 入口",
      gatewayDescription: "使用 Rotor 创建的 API Key，即可通过以下兼容协议调用已接入的模型。",
      baseUrl: "服务地址",
      protocol: "协议",
      endpoint: "调用地址",
      endpoints: "协议端点",
      refresh: "刷新",
      search: "搜索",
      addChannel: "新增渠道",
      channelsDescription: "管理上游服务的 API Key、模型和分发规则。",
      createKey: "创建 API Key",
      keyDescription: "请妥善保管您的 API Key，勿与他人共享或暴露于浏览器及客户端代码中。",
      keyUsedFor: "该 Key 用于客户端调用 Rotor 的统一 API，不是上游服务的 Key。",
      keyName: "Key 名称",
      keyNamePlaceholder: "例如：生产环境 / 移动端",
      userOptional: "用户标识（可选）",
      group: "分组",
      quotaOptional: "配额（可选）",
      allowedChannels: "允许的渠道 ID，逗号分隔（留空表示全部）",
      generateKey: "生成 Key",
      addChannelTitle: "新增模型渠道",
      addChannelDescription: "配置一个上游 API Key 及其可用模型。",
      close: "关闭",
      name: "名称",
      provider: "服务商",
      upstreamBaseUrl: "上游 Base URL",
      upstreamApiKey: "上游 API Key",
      authType: "鉴权方式",
      modelsPath: "模型列表路径",
      requestPath: "模型调用路径",
      priority: "优先级",
      weight: "权重",
      models: "模型列表",
      modelMapping: "模型映射 JSON",
      extra: "附加配置 JSON",
      enabled: "启用",
      probeModels: "探测模型",
      saveChannel: "保存渠道",
      saving: "保存中...",
      copy: "复制",
      copied: "已复制",
      view: "查看",
      createdAt: "创建时间",
      test: "测试",
      testing: "测试中...",
      edit: "编辑",
      editChannel: "编辑渠道",
      editToken: "编辑 Token",
      keepUnchanged: "留空表示不修改",
      expireTime: "过期时间",
      expired: "已过期",
      save: "保存",
      cancel: "取消",
      disable: "停用",
      enable: "启用",
      delete: "删除",
      resetUsage: "重置用量",
      updated: "已更新",
      deleted: "已删除",
      unlimited: "不限",
      created: "创建成功",
      generated: "API Key 已生成并复制到剪贴板",
      keyCopied: "Key 已复制到剪贴板",
      viewKey: "查看 API Key",
      deleteKeyTitle: "删除 API Key",
      deleteKeyWarning: "删除后该 Key 立即失效，且已接入的客户端将无法继续调用 Rotor，此操作不可撤销。",
      deleteKeyNameLabel: "即将删除",
      confirmDelete: "确认删除",
      securityTip: "安全提示",
      securityTipBody: "该 API Key 仅在此处显示一次，关闭后只能查看掩码。请勿提交到代码仓库或聊天工具。",
      copyKey: "复制 Key",
      closeAfterCopy: "我已保存，关闭",
      confirmDeleteChannel: "确定删除渠道",
      confirmDeleteKey: "确定删除 API Key",
      reachable: "可访问",
      failed: "失败",
      successLabel: "成功",
      failedLabel: "失败",
      successRate: "成功率",
      foundModels: "个模型，耗时",
      requireProbeFields: "探测模型前请先填写上游 Base URL 和 API Key",
      healthy: "系统健康",
      degraded: "部分降级",
      down: "全部异常",
      channelsEnabled: "个渠道启用",
      searchPlaceholder: "搜索名称 / 服务商 / 模型...",
      allProviders: "全部服务商",
      allStatus: "全部状态",
      noChannels: "暂无渠道",
      noChannelsHint: "点击右上角「新增渠道」开始接入",
      noTokens: "暂无 API Key",
      noLogs: "暂无日志记录",
      noData: "暂无数据",
      usageHint: "过去一段时间的请求量与 Token 趋势",
      timeline: "请求量 & Token 趋势",
      modelDist: "模型请求分布",
      channelSuccess: "渠道成功率",
      buckets: "个时间桶",
      chartUnavailable: "图表库未加载",
      allModels: "全部模型",
      tokenByModel: "按模型的 Token 消耗",
      allChannels: "全部渠道",
      clearFilter: "清除筛选",
      filteredHint: "当前筛选高亮",
      searchError: "搜索错误信息 / 模型...",
      logsHint: "最近 50 条请求记录",
      autoRefresh: "自动刷新",
      autoRefreshOn: "已开启自动刷新（每 5 秒）",
      columns: {
        name: "名称", provider: "服务商 / 协议", baseUrl: "上游地址", models: "模型",
        route: "分发", status: "状态", requests: "请求", actions: "操作",
        id: "ID", key: "API Key", user: "用户", quota: "配额", used: "已用",
        time: "时间", token: "Key", channel: "渠道", tokens: "Token 数",
        error: "错误", latency: "延迟",
      },
      metrics: ["请求数", "成功", "失败", "Token 总数", "输入 Token", "输出 Token", "费用", "平均延迟"],
      cacheHitRate: "缓存命中率",
      cacheHitTokens: "缓存命中",
      modelTableTitle: "按模型明细",
      modelTableHint: "输入 / 输出 / 缓存命中按模型拆分",
    },
    en: {
      pageTitle: "Rotor Admin",
      subtitle: "Model channels, API keys, usage, and request logs",
      language: "中文",
      overview: "API Access",
      channels: "Channels",
      apiKeys: "API Keys",
      usage: "Usage",
      logs: "Logs",
      mindagentChat: "MindAgent Chat",
      conversations: "Conversations",
      newConversation: "New chat",
      deleteConversation: "Delete conversation",
      confirmDeleteConversation: "Delete this local conversation?",
      model: "Model",
      selectModel: "Select model",
      selectModelFirst: "Select an available model first",
      noModelsAvailable: "No models available",
      agentReady: "Ready",
      agentThinking: "Thinking…",
      mindagentUnavailable: "MindAgent is not installed",
      chatTokenUnavailable: "Create a Rotor API key first",
      chatServiceUnavailable: "Chat service unavailable",
      chatPlaceholder: "Message MindAgent…",
      addAttachment: "Add content",
      addPhoto: "Add photos",
      addPhotoHint: "JPG, PNG, GIF, or WebP",
      addFile: "Add files",
      addFileHint: "Text, code, JSON, or CSV",
      webSearch: "Web search",
      comingSoon: "Coming soon",
      webSearchComingSoon: "Web search is not implemented yet",
      removeAttachment: "Remove attachment",
      tooManyAttachments: "You can attach up to 6 items",
      attachmentsTooLarge: "Attachments must be 10 MB or smaller in total",
      imageTooLarge: "Images must be 5 MB or smaller",
      fileTooLarge: "Files must be 500 KB or smaller",
      unsupportedFileType: "Only text, code, and structured data files are supported",
      fileReadFailed: "Could not read the file",
      defaultAttachmentPrompt: "Please analyze these attachments.",
      sendMessage: "Send message",
      stopGenerating: "Stop generating",
      chatHint: "Enter to send, Shift + Enter for a new line. Verify important AI output.",
      chatWelcome: "How can I help?",
      chatWelcomeDescription: "Chat continuously with MindAgent through Rotor's configured model channels.",
      chatSuggestionOne: "Tell me what you can help me do",
      chatSuggestionTwo: "Help me outline a technical design",
      chatSuggestionThree: "Explain a complex concept",
      you: "You",
      chatFailed: "Generation failed",
      emptyResponse: "The model returned no content.",
      generationStopped: "Generation stopped.",
      streamUnavailable: "Streaming responses are not supported by this browser",
      copyFailed: "Copy failed",
      settings: "Settings",
      settingsDescription: "Configure Rotor runtime options.",
      routingSettings: "Routing",
      routingSettingsDescription: "Control channel selection and session affinity.",
      routingStrategy: "Routing strategy",
      strategyPriorityWeighted: "Priority + weighted distribution",
      strategyFallbackOrder: "Fixed fallback order",
      strategyWeighted: "Global weighted distribution",
      affinityEnabled: "Enable session affinity",
      affinityDescription: "Keep a session on one channel when distributing traffic; fixed fallback order is unaffected.",
      settingsFile: "Settings file",
      saveSettings: "Save settings",
      settingsSaved: "Settings saved and applied",
      gatewayTitle: "Unified API Endpoints",
      gatewayDescription: "Use an API key created by Rotor to call all connected models through these compatible protocols.",
      baseUrl: "Base URL",
      protocol: "Protocol",
      endpoint: "Endpoint",
      endpoints: "Endpoints",
      refresh: "Refresh",
      search: "Search",
      addChannel: "Add Channel",
      channelsDescription: "Manage upstream API keys, models, and routing rules.",
      createKey: "Create API Key",
      keyDescription: "Keep your API key safe — do not share it or expose it in browsers or client-side code.",
      keyUsedFor: "This key is used by clients to call Rotor's unified API, not by upstream providers.",
      keyName: "Key name",
      keyNamePlaceholder: "e.g. Production / Mobile App",
      userOptional: "User ID (optional)",
      group: "Group",
      quotaOptional: "Quota (optional)",
      allowedChannels: "Allowed channel IDs, comma separated (blank means all)",
      generateKey: "Generate Key",
      addChannelTitle: "Add Model Channel",
      addChannelDescription: "Configure one upstream API key and its available models.",
      close: "Close",
      name: "Name",
      provider: "Provider",
      upstreamBaseUrl: "Upstream Base URL",
      upstreamApiKey: "Upstream API Key",
      authType: "Authentication",
      modelsPath: "Models Path",
      requestPath: "Request Path",
      priority: "Priority",
      weight: "Weight",
      models: "Models",
      modelMapping: "Model Mapping JSON",
      extra: "Extra Config JSON",
      enabled: "Enabled",
      probeModels: "Probe Models",
      saveChannel: "Save Channel",
      saving: "Saving...",
      copy: "Copy",
      copied: "Copied",
      view: "View",
      createdAt: "Created at",
      test: "Test",
      testing: "Testing...",
      edit: "Edit",
      editChannel: "Edit channel",
      editToken: "Edit token",
      keepUnchanged: "Leave blank to keep current",
      expireTime: "Expires at",
      expired: "expired",
      save: "Save",
      cancel: "Cancel",
      disable: "Disable",
      enable: "Enable",
      delete: "Delete",
      resetUsage: "Reset Usage",
      updated: "Updated",
      deleted: "Deleted",
      unlimited: "Unlimited",
      created: "created",
      generated: "API key generated and copied to clipboard",
      keyCopied: "Key copied to clipboard",
      viewKey: "View API Key",
      deleteKeyTitle: "Delete API Key",
      deleteKeyWarning: "Once deleted, this key stops working immediately and clients using it will lose access. This cannot be undone.",
      deleteKeyNameLabel: "Deleting",
      confirmDelete: "Delete",
      securityTip: "Security tip",
      securityTipBody: "This key is shown in full only once. After closing, only the masked form is available. Do not commit it to repos or paste into chat tools.",
      copyKey: "Copy key",
      closeAfterCopy: "Saved, close",
      confirmDeleteChannel: "Delete channel",
      confirmDeleteKey: "Delete API key",
      reachable: "reachable",
      failed: "failed",
      successLabel: "ok",
      failedLabel: "fail",
      successRate: "Success rate",
      foundModels: "models found in",
      requireProbeFields: "Enter the upstream Base URL and API key before probing models",
      healthy: "Healthy",
      degraded: "Degraded",
      down: "Down",
      channelsEnabled: "channels on",
      searchPlaceholder: "Search name / provider / model...",
      allProviders: "All providers",
      allStatus: "All status",
      noChannels: "No channels yet",
      noChannelsHint: "Click \"Add Channel\" to get started",
      noTokens: "No API keys yet",
      noLogs: "No logs yet",
      noData: "No data",
      usageHint: "Request and token trends over the selected window",
      timeline: "Requests & Tokens",
      modelDist: "Model distribution",
      channelSuccess: "Channel success rate",
      buckets: "buckets",
      chartUnavailable: "Chart library not loaded",
      allModels: "All models",
      tokenByModel: "Token usage by model",
      allChannels: "All channels",
      clearFilter: "Clear filter",
      filteredHint: "filtered highlight",
      searchError: "Search error / model...",
      logsHint: "Last 50 request logs",
      autoRefresh: "Auto refresh",
      autoRefreshOn: "Auto refresh on (every 5s)",
      columns: {
        name: "Name", provider: "Provider / Protocol", baseUrl: "Upstream URL", models: "Models",
        route: "Route", status: "Status", requests: "Requests", actions: "Actions",
        id: "ID", key: "API Key", user: "User", quota: "Quota", used: "Used",
        time: "Time", token: "Key", channel: "Channel", tokens: "Tokens",
        error: "Error", latency: "Latency",
      },
      metrics: ["Requests", "Success", "Failed", "Total Tokens", "Prompt Tokens", "Completion Tokens", "Cost", "Avg Latency"],
      cacheHitRate: "Cache hit rate",
      cacheHitTokens: "Cache hits",
      modelTableTitle: "Per-model breakdown",
      modelTableHint: "Input / output / cache hits by model",
    },
  },
};
