window.ROTOR_UI_CONFIG = {
  defaultLocale: "zh-CN",
  locales: {
    "zh-CN": {
      pageTitle: "Rotor 管理控制台",
      subtitle: "模型渠道、API Key、用量与请求日志",
      adminLoginTitle: "管理员登录",
      adminLoginDescription: "登录 Rotor 管理控制台。首次登录后必须修改默认密码。",
      adminUsername: "用户名",
      adminPassword: "密码",
      adminLoginFailed: "用户名或密码错误",
      adminLoginRateLimited: "登录尝试过多，请稍后重试",
      adminSessionExpired: "管理员会话已过期，请重新登录",
      adminServiceUnavailable: "无法连接 Rotor 管理服务",
      changePasswordTitle: "修改默认密码",
      changePasswordDescription: "为了继续使用管理控制台，请设置不少于 6 个字符的新密码。",
      currentPassword: "当前密码",
      newPassword: "新密码",
      confirmPassword: "确认新密码",
      passwordMismatch: "两次输入的新密码不一致",
      passwordChangeFailed: "密码修改失败，请检查当前密码",
      savePassword: "保存新密码",
      signIn: "登录",
      signOut: "退出登录",
      language: "English",
      overview: "接入信息",
      channels: "模型渠道",
      apiKeys: "API Key",
      mcpControlKeys: "MCP Control Key",
      mcpControlKeysDescription: "用于 Codex、MindCode 等 MCP 客户端访问 Rotor 的只读诊断能力。",
      createMcpControlKey: "新建控制密钥",
      noMcpControlKeys: "暂无 MCP Control Key",
      mcpControlKey: "控制密钥",
      mcpControlKeyNamePlaceholder: "例如：本机 Codex",
      mcpControlKeyConfig: "MCP 环境变量",
      copyMcpConfig: "复制 MCP 配置",
      mcpControlKeyGenerated: "MCP Control Key 已生成并复制到剪贴板",
      mcpControlKeySecurityTip: "该密钥仅显示一次，可访问 Rotor 的只读诊断数据。请妥善保存，不要提交到代码仓库。",
      deleteMcpControlKeyTitle: "删除 MCP Control Key",
      deleteMcpControlKeyWarning: "删除后，使用此密钥的 MCP 客户端将立即无法访问 Rotor。此操作不可撤销。",
      usage: "用量统计",
      logs: "请求日志",
      monitoringTitle: "监控",
      monitoringSessionSources: "客户端来源",
      perfTitle: "性能",
      perfDescription: "查看请求处理、数据库耗时与后台归档状态。",
      perfAutoRefresh: "每 10 秒刷新",
      perfRefreshing: "刷新中…",
      perfRequests: "请求数",
      perfSinceStart: "进程启动以来",
      perfAcquire: "数据库连接获取",
      perfQueue: "归档队列",
      perfPendingEvents: "待处理 / 容量",
      perfReconciliation: "增量对账",
      perfIncremental: "从对账基线开始",
      perfDatabase: "数据库耗时",
      perfMetric: "指标",
      perfSamples: "窗口样本",
      perfTotalCount: "累计次数",
      perfSql: "SQL 执行",
      perfCommit: "数据库提交",
      perfHold: "连接持有",
      perfDatabaseHint: "连接获取包含等待和创建；提交耗时不包含 flush。",
      perfArchive: "后台归档",
      perfBatchSize: "批次事件数",
      perfBatchTime: "批次耗时",
      perfQueueWait: "队列等待",
      perfDrain: "队列排空",
      perfQueueDrops: "队列满丢弃",
      perfRetryDrops: "重试耗尽丢弃",
      perfNoData: "暂无数据",
      perfNoDataHint: "尚未取得对账结果。",
      perfDisabled: "未启用",
      perfRunning: "运行中",
      perfStopped: "已停止",
      perfProtocols: "协议请求",
      perfProtocol: "协议",
      perfSuccess: "成功",
      perfSuccessRate: "成功率",
      perfFailed: "失败",
      perfCancelled: "取消",
      perfLatency: "请求耗时",
      perfOther: "其他",
      perfProtocolHint: "结果次数为进程累计；n 为当前窗口样本数。TTFT 仅统计流式请求，无样本显示 —。",
      perfBaseline: "基线已建立",
      perfBaselinePending: "等待建立基线",
      perfBaselinePendingHint: "下一次检查将建立新的对账基线，尚未验证账务一致性。",
      perfBaselineHint: "等待下一次检查比较增量；此状态不代表账务已验证一致。",
      perfOk: "增量一致",
      perfOkHint: "本次检查中，账本与 Token 计数的增量一致。",
      perfMismatch: "增量不一致",
      perfMismatchHint: "账本与 Token 计数的增量存在差异，请检查请求记账与计数重置。",
      perfInvalid: "基线已失效",
      perfInvalidHint: "当前计数无法与原基线比较；请确认原因后重新建立基线。",
      perfError: "检查失败",
      perfErrorHint: "本次检查未完成，不能据此判断账务是否一致。",
      perfLedger: "账本",
      perfTokenCounters: "Token 计数",
      perfQuota: "已用额度",
      perfTokens: "Token 总量",
      perfBaselineSince: "基线时间",
      perfCheckedAt: "检查时间",
      perfCacheNote: "结果最多缓存 30 秒",
      perfCached: "缓存结果",
      perfResetBaseline: "重建对账基线",
      perfResetHint: "重建基线只重新开始比较，不修改账务数据，也不修复已有差异。",
      perfSampleNote: "分位数：最近窗口 / 每项最多样本",
      perfCumulativeNote: "累计次数自当前进程启动；多进程数据不合并。",
      perfProcess: "进程 PID",
      perfStartedAt: "启动时间",
      perfLoadFailed: "性能数据加载失败",
      perfReconciliationFailed: "对账数据加载失败",
      perfDifferentProcess: "性能快照与对账来自不同进程，请分别查看各自 PID 与启动时间。",
      monitoringSources: "监控源",
      monitoringSourcesDescription: "按客户端标识统计今日请求；无会话 ID 的请求也计入，路由重试不重复计数。",
      todayRequests: "今日请求",
      ungroupedRequests: "无会话 ID 请求",
      requestsSeen: "今日有请求",
      noRequestsSeen: "今日暂无请求",
      monitoringSnapshot: "监控统计口径",
      monitoringDate: "统计日期",
      monitoringTimezone: "时区",
      monitoringUpdatedAt: "数据更新时间",
      todaySessions: "今日 Session",
      activeSessions: "活跃 Session",
      todayTokens: "今日 Token",
      requestTurns: "请求轮次",
      active: "活跃",
      inactive: "不活跃",
      noMonitoringSources: "今日暂无 Coding Agent Session",
      noMonitoringSourcesHint: "当 Coding Agent 通过 Rotor 发起请求后，聚合统计将显示在这里。",
      monitoringLoadFailed: "监控源加载失败",
      mindagentChat: "MindAgent 对话",
      conversations: "对话记录",
      recentConversations: "最近对话",
      newConversation: "新对话",
      deleteConversation: "删除对话",
      exportConversation: "导出 JSON",
      confirmDeleteConversation: "确定删除这条本地对话记录吗？",
      model: "模型",
      selectModel: "选择模型",
      selectModelFirst: "请先选择一个可用模型",
      noModelsAvailable: "暂无可用模型",
      agentReady: "已就绪",
      agentThinking: "正在思考…",
      mindagentUnavailable: "MindAgent 尚未安装",
      chatTokenUnavailable: "请先创建 Rotor API Key",
      chatServiceUnavailable: "聊天服务不可用",
      chatPlaceholder: "给 MindAgent 发送消息…",
      addAttachment: "添加内容",
      addPhoto: "添加照片",
      addPhotoHint: "JPG、PNG、GIF 或 WebP",
      addFile: "添加文件",
      addFileHint: "文本、代码、JSON 或 CSV",
      webSearch: "网页搜索",
      comingSoon: "即将支持",
      webSearchComingSoon: "网页搜索功能暂未实现",
      removeAttachment: "移除附件",
      tooManyAttachments: "一次最多添加 6 个附件",
      attachmentsTooLarge: "附件总大小不能超过 10 MB",
      imageTooLarge: "图片不能超过 5 MB",
      fileTooLarge: "文件不能超过 500 KB",
      unsupportedFileType: "当前仅支持文本、代码和结构化数据文件",
      fileReadFailed: "无法读取文件",
      defaultAttachmentPrompt: "请分析这些附件。",
      sendMessage: "发送消息",
      stopGenerating: "停止生成",
      chatHint: "Enter 发送，Shift + Enter 换行。AI 输出可能存在错误，请核对重要信息。",
      chatWelcome: "有什么可以帮你？",
      chatWelcomeDescription: "通过 Rotor 已配置的模型渠道，与 MindAgent 进行连续对话。",
      chatSuggestionOne: "介绍一下你能帮我完成什么",
      chatSuggestionTwo: "帮我梳理一个技术方案",
      chatSuggestionThree: "解释一段复杂概念",
      you: "你",
      chatFailed: "生成失败",
      emptyResponse: "模型没有返回内容。",
      generationStopped: "已停止生成。",
      streamUnavailable: "浏览器不支持流式响应",
      copyFailed: "复制失败",
      settings: "设置",
      settingsDescription: "配置 Rotor 的运行参数。",
      routingSettings: "路由设置",
      routingSettingsDescription: "控制多个渠道之间的选择方式和会话粘性。",
      routingStrategy: "路由策略",
      strategyPriorityWeighted: "优先级 + 权重分摊",
      strategyFallbackOrder: "固定主备顺序",
      strategyWeighted: "全局权重分摊",
      affinityEnabled: "启用会话亲和",
      affinityDescription: "为尚无租约的会话提供稳定分配；关闭后 Session Lease 也停用。",
      sessionLeaseEnabled: "启用 Session Lease",
      sessionLeaseDescription: "将活跃会话固定在最后成功的渠道，fallback 成功后迁移；关闭会话亲和时同时失效。",
      sessionLeaseIdleTtl: "Session Lease 空闲 TTL（秒）",
      sessionLeaseIdleTtlDescription: "租约在最后一次成功请求后保持的时间；可在 Channel extra 中按渠道或模型覆盖。",
      settingsFile: "配置文件",
      saveSettings: "保存设置",
      settingsSaved: "设置已保存并立即生效",
      displayTimezone: "日期与时间",
      displayTimezoneDescription: "用于用量和请求日志的自然日边界与日期范围。",
      gatewayTitle: "统一 API 入口",
      gatewayDescription: "使用 Rotor 创建的 API Key，即可通过以下兼容协议调用已接入的模型。",
      baseUrl: "服务地址",
      protocol: "协议",
      endpoint: "调用地址",
      endpoints: "协议端点",
      refresh: "刷新",
      search: "搜索",
      addChannel: "新增渠道",
      channelsDescription: "管理上游服务的 API Key、模型和分发规则。",
      createKey: "创建 API Key",
      keyDescription: "请妥善保管您的 API Key，勿与他人共享或暴露于浏览器及客户端代码中。",
      keyUsedFor: "该 Key 用于客户端调用 Rotor 的统一 API，不是上游服务的 Key。",
      keyName: "Key 名称",
      keyNamePlaceholder: "例如：生产环境 / 移动端",
      userOptional: "用户标识（可选）",
      group: "分组",
      quotaOptional: "配额（可选）",
      allowedChannels: "允许的渠道 ID，逗号分隔（留空表示全部）",
      generateKey: "生成 Key",
      addChannelTitle: "新增模型渠道",
      addChannelDescription: "配置一个上游 API Key 及其可用模型。",
      close: "关闭",
      name: "名称",
      provider: "服务商",
      upstreamBaseUrl: "上游 Base URL",
      upstreamApiKey: "上游 API Key",
      authType: "鉴权方式",
      modelsPath: "模型列表路径",
      requestPath: "模型调用路径",
      priority: "优先级",
      weight: "权重",
      models: "模型列表",
      modelMapping: "模型映射 JSON",
      extra: "附加配置 JSON",
      enabled: "启用",
      probeModels: "探测模型",
      probing: "探测中...",
      saveChannel: "保存渠道",
      saving: "保存中...",
      copy: "复制",
      copied: "已复制",
      view: "查看",
      createdAt: "创建时间",
      test: "测试",
      testing: "测试中...",
      edit: "编辑",
      editChannel: "编辑渠道",
      editToken: "编辑 Token",
      keepUnchanged: "留空表示不修改",
      expireTime: "过期时间",
      expired: "已过期",
      save: "保存",
      cancel: "取消",
      disable: "停用",
      enable: "启用",
      delete: "删除",
      resetUsage: "重置用量",
      updated: "已更新",
      deleted: "已删除",
      unlimited: "不限",
      created: "创建成功",
      generated: "API Key 已生成并复制到剪贴板",
      keyCopied: "Key 已复制到剪贴板",
      viewKey: "查看 API Key",
      deleteKeyTitle: "删除 API Key",
      deleteKeyWarning: "删除后该 Key 立即失效，且已接入的客户端将无法继续调用 Rotor，此操作不可撤销。",
      deleteKeyNameLabel: "即将删除",
      confirmDelete: "确认删除",
      securityTip: "安全提示",
      securityTipBody: "该 API Key 仅在此处显示一次，关闭后只能查看掩码。请勿提交到代码仓库或聊天工具。",
      copyKey: "复制 Key",
      closeAfterCopy: "我已保存，关闭",
      confirmDeleteChannel: "确定删除渠道",
      confirmDeleteKey: "确定删除 API Key",
      reachable: "可访问",
      modelCatalogReachable: "模型目录可访问（未验证生成）",
      failed: "失败",
      successLabel: "成功",
      failedLabel: "失败",
      successRate: "成功率",
      foundModels: "个模型，耗时",
      requireProbeFields: "探测模型前请先填写上游 Base URL 和 API Key",
      probeNoModels: "上游返回的模型列表为空，未更新渠道",
      confirmUpdateModels: "是否用探测到的模型列表更新该渠道？",
      currentLabel: "当前模型",
      healthy: "系统健康",
      degraded: "部分降级",
      down: "全部异常",
      idle: "空闲",
      last7Days: "最近 7 天",
      systemStatus: "运行状态",
      systemStatusHint: "基于最近 15 分钟的真实请求",
      recentRequests: "近 15 分钟请求",
      lastSuccess: "最近成功",
      noRecentTraffic: "最近 15 分钟没有请求",
      allRecentRequestsSucceeded: "最近请求全部成功",
      someRecentRequestsFailed: "部分最近请求失败",
      allRecentRequestsFailed: "最近请求全部失败",
      noSuccessfulRequests: "暂无成功请求",
      recentFailures: "近期异常",
      recentFailuresHint: "最近 24 小时的失败请求",
      noRecentFailures: "最近 24 小时没有失败请求",
      viewAllLogs: "查看全部日志",
      channelsEnabled: "个渠道启用",
      searchPlaceholder: "搜索名称 / 服务商 / 模型...",
      allProviders: "全部服务商",
      allStatus: "全部状态",
      noChannels: "暂无渠道",
      noChannelsHint: "点击右上角「新增渠道」开始接入",
      noTokens: "暂无 API Key",
      noLogs: "暂无日志记录",
      noData: "暂无数据",
      usageHint: "过去一段时间的请求量与 Token 趋势",
      startDate: "开始日期",
      endDate: "结束日期",
      customDateRange: "自定义",
      invalidDateRange: "开始日期不能晚于结束日期，请选择完整的日期范围",
      futureEndDate: "结束日期不能晚于今天",
      timeline: "请求量 & Token 趋势",
      modelDist: "模型请求分布",
      channelSuccess: "渠道成功率",
      buckets: "个时间桶",
      chartUnavailable: "图表库未加载",
      allModels: "全部模型",
      tokenByModel: "按模型的 Token 消耗",
      allChannels: "全部渠道",
      clearFilter: "清除筛选",
      filteredHint: "当前筛选高亮",
      searchError: "搜索错误信息 / 模型...",
      logsHint: "最近 50 条请求记录",
      requestTrend: "请求趋势",
      requestCount: "请求数",
      logDetails: "查看详情",
      logDetailFailed: "加载详情失败",
      retry: "重试",
      autoRefresh: "自动刷新",
      autoRefreshOn: "已开启自动刷新（每 5 秒）",
      columns: {
        name: "名称", provider: "服务商 / 协议", baseUrl: "上游地址", models: "模型",
        route: "分发", status: "状态", requests: "请求", actions: "操作",
        id: "ID", key: "API Key", user: "用户", quota: "配额", used: "已用",
        time: "时间", token: "Key", channel: "渠道", tokens: "Token 数",
        error: "错误", latency: "延迟",
      },
      metrics: ["请求数", "成功", "失败", "Token 总数", "输入 Token", "输出 Token", "费用", "平均延迟"],
      cacheHitRate: "缓存命中率",
      cacheHitTokens: "缓存命中",
      modelTableTitle: "按模型明细",
      modelTableHint: "输入 / 输出 / 缓存命中按模型拆分",
    },
    en: {
      pageTitle: "Rotor Admin",
      subtitle: "Model channels, API keys, usage, and request logs",
      adminLoginTitle: "Admin sign in",
      adminLoginDescription: "Sign in to Rotor. You must change the default password after the first login.",
      adminUsername: "Username",
      adminPassword: "Password",
      adminLoginFailed: "Invalid username or password",
      adminLoginRateLimited: "Too many login attempts. Try again later.",
      adminSessionExpired: "Your admin session expired. Sign in again.",
      adminServiceUnavailable: "Unable to reach the Rotor admin service",
      changePasswordTitle: "Change the default password",
      changePasswordDescription: "Set a new password with at least 6 characters before continuing.",
      currentPassword: "Current password",
      newPassword: "New password",
      confirmPassword: "Confirm new password",
      passwordMismatch: "The new passwords do not match",
      passwordChangeFailed: "Unable to change the password. Check the current password.",
      savePassword: "Save new password",
      signIn: "Sign in",
      signOut: "Sign out",
      language: "中文",
      overview: "API Access",
      channels: "Channels",
      apiKeys: "API Keys",
      mcpControlKeys: "MCP Control Keys",
      mcpControlKeysDescription: "Read-only diagnostic credentials for Codex, MindCode, and other MCP clients.",
      createMcpControlKey: "Create Control Key",
      noMcpControlKeys: "No MCP Control Keys",
      mcpControlKey: "Control Key",
      mcpControlKeyNamePlaceholder: "For example: Local Codex",
      mcpControlKeyConfig: "MCP environment variables",
      copyMcpConfig: "Copy MCP config",
      mcpControlKeyGenerated: "MCP Control Key generated and copied to clipboard",
      mcpControlKeySecurityTip: "This key is shown once and grants access to Rotor's read-only diagnostic data. Store it safely and never commit it to a repository.",
      deleteMcpControlKeyTitle: "Delete MCP Control Key",
      deleteMcpControlKeyWarning: "Clients using this key will immediately lose access to Rotor. This action cannot be undone.",
      usage: "Usage",
      logs: "Logs",
      monitoringTitle: "Monitoring",
      monitoringSessionSources: "Client sources",
      perfTitle: "Performance",
      perfDescription: "Request handling, database timings, and background archiving.",
      perfAutoRefresh: "Refresh every 10 seconds",
      perfRefreshing: "Refreshing…",
      perfRequests: "Requests",
      perfSinceStart: "Since process start",
      perfAcquire: "Connection acquisition",
      perfQueue: "Archive queue",
      perfPendingEvents: "Pending / capacity",
      perfReconciliation: "Incremental reconciliation",
      perfIncremental: "Since reconciliation baseline",
      perfDatabase: "Database timings",
      perfMetric: "Metric",
      perfSamples: "Window samples",
      perfTotalCount: "Total count",
      perfSql: "SQL execution",
      perfCommit: "Database commit",
      perfHold: "Connection hold",
      perfDatabaseHint: "Acquisition includes waiting and creation; commit time excludes flush.",
      perfArchive: "Background archive",
      perfBatchSize: "Events per batch",
      perfBatchTime: "Batch duration",
      perfQueueWait: "Queue wait",
      perfDrain: "Queue drain",
      perfQueueDrops: "Dropped: queue full",
      perfRetryDrops: "Dropped: retries exhausted",
      perfNoData: "No data",
      perfNoDataHint: "No reconciliation result has been received yet.",
      perfDisabled: "Disabled",
      perfRunning: "Running",
      perfStopped: "Stopped",
      perfProtocols: "Requests by protocol",
      perfProtocol: "Protocol",
      perfSuccess: "Success",
      perfSuccessRate: "Success rate",
      perfFailed: "Failed",
      perfCancelled: "Cancelled",
      perfLatency: "Latency",
      perfOther: "Other",
      perfProtocolHint: "Outcome counts are process totals; n is the window sample count. TTFT covers streams only; no samples are shown as —.",
      perfBaseline: "Baseline ready",
      perfBaselinePending: "Awaiting baseline",
      perfBaselinePendingHint: "The next check will establish a new baseline; this does not yet confirm consistency.",
      perfBaselineHint: "Waiting for the next incremental comparison; this does not yet confirm consistency.",
      perfOk: "Deltas match",
      perfOkHint: "Ledger and Token counter deltas match for this check.",
      perfMismatch: "Deltas differ",
      perfMismatchHint: "Ledger and Token deltas differ. Check request accounting and counter resets.",
      perfInvalid: "Baseline invalid",
      perfInvalidHint: "Current counters cannot be compared with this baseline. Review the cause, then reset it.",
      perfError: "Check failed",
      perfErrorHint: "This check did not complete; consistency cannot be determined.",
      perfLedger: "Ledger",
      perfTokenCounters: "Token counters",
      perfQuota: "Used quota",
      perfTokens: "Total tokens",
      perfBaselineSince: "Baseline since",
      perfCheckedAt: "Checked at",
      perfCacheNote: "Results cached for up to 30 seconds",
      perfCached: "Cached result",
      perfResetBaseline: "Reset reconciliation baseline",
      perfResetHint: "Resetting only restarts the comparison; it does not change accounting data or fix differences.",
      perfSampleNote: "Percentiles: recent window / maximum samples per metric",
      perfCumulativeNote: "Counts accumulate since this process started; processes are not combined.",
      perfProcess: "Process PID",
      perfStartedAt: "Started at",
      perfLoadFailed: "Could not load performance data",
      perfReconciliationFailed: "Could not load reconciliation data",
      perfDifferentProcess: "Performance and reconciliation came from different processes. Check their respective PIDs and start times.",
      monitoringSources: "Monitoring Sources",
      monitoringSourcesDescription: "Today’s requests by client identity, including requests without session IDs. Routing retries count once.",
      todayRequests: "Today’s Requests",
      ungroupedRequests: "Requests Without Session ID",
      requestsSeen: "Requests received today",
      noRequestsSeen: "No requests today",
      monitoringSnapshot: "Monitoring scope",
      monitoringDate: "Data date",
      monitoringTimezone: "Timezone",
      monitoringUpdatedAt: "Updated at",
      todaySessions: "Today's Sessions",
      activeSessions: "Active Sessions",
      todayTokens: "Today's Tokens",
      requestTurns: "Request Turns",
      active: "Active",
      inactive: "Inactive",
      noMonitoringSources: "No Coding Agent sessions today",
      noMonitoringSourcesHint: "Aggregate statistics are available after a Coding Agent sends requests through Rotor.",
      monitoringLoadFailed: "Failed to load monitoring sources",
      mindagentChat: "MindAgent Chat",
      conversations: "Conversations",
      recentConversations: "Recent chats",
      newConversation: "New chat",
      deleteConversation: "Delete conversation",
      exportConversation: "Export JSON",
      confirmDeleteConversation: "Delete this local conversation?",
      model: "Model",
      selectModel: "Select model",
      selectModelFirst: "Select an available model first",
      noModelsAvailable: "No models available",
      agentReady: "Ready",
      agentThinking: "Thinking…",
      mindagentUnavailable: "MindAgent is not installed",
      chatTokenUnavailable: "Create a Rotor API key first",
      chatServiceUnavailable: "Chat service unavailable",
      chatPlaceholder: "Message MindAgent…",
      addAttachment: "Add content",
      addPhoto: "Add photos",
      addPhotoHint: "JPG, PNG, GIF, or WebP",
      addFile: "Add files",
      addFileHint: "Text, code, JSON, or CSV",
      webSearch: "Web search",
      comingSoon: "Coming soon",
      webSearchComingSoon: "Web search is not implemented yet",
      removeAttachment: "Remove attachment",
      tooManyAttachments: "You can attach up to 6 items",
      attachmentsTooLarge: "Attachments must be 10 MB or smaller in total",
      imageTooLarge: "Images must be 5 MB or smaller",
      fileTooLarge: "Files must be 500 KB or smaller",
      unsupportedFileType: "Only text, code, and structured data files are supported",
      fileReadFailed: "Could not read the file",
      defaultAttachmentPrompt: "Please analyze these attachments.",
      sendMessage: "Send message",
      stopGenerating: "Stop generating",
      chatHint: "Enter to send, Shift + Enter for a new line. Verify important AI output.",
      chatWelcome: "How can I help?",
      chatWelcomeDescription: "Chat continuously with MindAgent through Rotor's configured model channels.",
      chatSuggestionOne: "Tell me what you can help me do",
      chatSuggestionTwo: "Help me outline a technical design",
      chatSuggestionThree: "Explain a complex concept",
      you: "You",
      chatFailed: "Generation failed",
      emptyResponse: "The model returned no content.",
      generationStopped: "Generation stopped.",
      streamUnavailable: "Streaming responses are not supported by this browser",
      copyFailed: "Copy failed",
      settings: "Settings",
      settingsDescription: "Configure Rotor runtime options.",
      routingSettings: "Routing",
      routingSettingsDescription: "Control channel selection and session affinity.",
      routingStrategy: "Routing strategy",
      strategyPriorityWeighted: "Priority + weighted distribution",
      strategyFallbackOrder: "Fixed fallback order",
      strategyWeighted: "Global weighted distribution",
      affinityEnabled: "Enable session affinity",
      affinityDescription: "Provide stable placement for sessions without a lease; disabling this also disables Session Lease.",
      sessionLeaseEnabled: "Enable Session Lease",
      sessionLeaseDescription: "Pin active sessions to their last successful channel and migrate after successful fallback; disabling affinity also disables leases.",
      sessionLeaseIdleTtl: "Session Lease idle TTL (seconds)",
      sessionLeaseIdleTtlDescription: "How long a lease remains active after the last successful request; Channel extra can override it per channel or model.",
      settingsFile: "Settings file",
      saveSettings: "Save settings",
      settingsSaved: "Settings saved and applied",
      displayTimezone: "Date & time",
      displayTimezoneDescription: "Controls calendar-day boundaries and date ranges for usage and request logs.",
      gatewayTitle: "Unified API Endpoints",
      gatewayDescription: "Use an API key created by Rotor to call all connected models through these compatible protocols.",
      baseUrl: "Base URL",
      protocol: "Protocol",
      endpoint: "Endpoint",
      endpoints: "Endpoints",
      refresh: "Refresh",
      search: "Search",
      addChannel: "Add Channel",
      channelsDescription: "Manage upstream API keys, models, and routing rules.",
      createKey: "Create API Key",
      keyDescription: "Keep your API key safe — do not share it or expose it in browsers or client-side code.",
      keyUsedFor: "This key is used by clients to call Rotor's unified API, not by upstream providers.",
      keyName: "Key name",
      keyNamePlaceholder: "e.g. Production / Mobile App",
      userOptional: "User ID (optional)",
      group: "Group",
      quotaOptional: "Quota (optional)",
      allowedChannels: "Allowed channel IDs, comma separated (blank means all)",
      generateKey: "Generate Key",
      addChannelTitle: "Add Model Channel",
      addChannelDescription: "Configure one upstream API key and its available models.",
      close: "Close",
      name: "Name",
      provider: "Provider",
      upstreamBaseUrl: "Upstream Base URL",
      upstreamApiKey: "Upstream API Key",
      authType: "Authentication",
      modelsPath: "Models Path",
      requestPath: "Request Path",
      priority: "Priority",
      weight: "Weight",
      models: "Models",
      modelMapping: "Model Mapping JSON",
      extra: "Extra Config JSON",
      enabled: "Enabled",
      probeModels: "Probe Models",
      probing: "Probing...",
      saveChannel: "Save Channel",
      saving: "Saving...",
      copy: "Copy",
      copied: "Copied",
      view: "View",
      createdAt: "Created at",
      test: "Test",
      testing: "Testing...",
      edit: "Edit",
      editChannel: "Edit channel",
      editToken: "Edit token",
      keepUnchanged: "Leave blank to keep current",
      expireTime: "Expires at",
      expired: "expired",
      save: "Save",
      cancel: "Cancel",
      disable: "Disable",
      enable: "Enable",
      delete: "Delete",
      resetUsage: "Reset Usage",
      updated: "Updated",
      deleted: "Deleted",
      unlimited: "Unlimited",
      created: "created",
      generated: "API key generated and copied to clipboard",
      keyCopied: "Key copied to clipboard",
      viewKey: "View API Key",
      deleteKeyTitle: "Delete API Key",
      deleteKeyWarning: "Once deleted, this key stops working immediately and clients using it will lose access. This cannot be undone.",
      deleteKeyNameLabel: "Deleting",
      confirmDelete: "Delete",
      securityTip: "Security tip",
      securityTipBody: "This key is shown in full only once. After closing, only the masked form is available. Do not commit it to repos or paste into chat tools.",
      copyKey: "Copy key",
      closeAfterCopy: "Saved, close",
      confirmDeleteChannel: "Delete channel",
      confirmDeleteKey: "Delete API key",
      reachable: "reachable",
      modelCatalogReachable: "Model catalog reachable (generation not verified)",
      failed: "failed",
      successLabel: "ok",
      failedLabel: "fail",
      successRate: "Success rate",
      foundModels: "models found in",
      requireProbeFields: "Enter the upstream Base URL and API key before probing models",
      probeNoModels: "Upstream returned an empty model list; channel not updated",
      confirmUpdateModels: "Update this channel's models to the probed list?",
      currentLabel: "Current models",
      healthy: "Healthy",
      degraded: "Degraded",
      down: "Down",
      idle: "Idle",
      last7Days: "Last 7 days",
      systemStatus: "System status",
      systemStatusHint: "Based on real requests from the last 15 minutes",
      recentRequests: "Requests in 15m",
      lastSuccess: "Last success",
      noRecentTraffic: "No requests in the last 15 minutes",
      allRecentRequestsSucceeded: "All recent requests succeeded",
      someRecentRequestsFailed: "Some recent requests failed",
      allRecentRequestsFailed: "All recent requests failed",
      noSuccessfulRequests: "No successful requests yet",
      recentFailures: "Recent failures",
      recentFailuresHint: "Failed requests in the last 24 hours",
      noRecentFailures: "No failed requests in the last 24 hours",
      viewAllLogs: "View all logs",
      channelsEnabled: "channels on",
      searchPlaceholder: "Search name / provider / model...",
      allProviders: "All providers",
      allStatus: "All status",
      noChannels: "No channels yet",
      noChannelsHint: "Click \"Add Channel\" to get started",
      noTokens: "No API keys yet",
      noLogs: "No logs yet",
      noData: "No data",
      usageHint: "Request and token trends over the selected window",
      startDate: "Start date",
      endDate: "End date",
      customDateRange: "Custom",
      invalidDateRange: "Start date cannot be after end date; select a complete date range",
      futureEndDate: "End date cannot be later than today",
      timeline: "Requests & Tokens",
      modelDist: "Model distribution",
      channelSuccess: "Channel success rate",
      buckets: "buckets",
      chartUnavailable: "Chart library not loaded",
      allModels: "All models",
      tokenByModel: "Token usage by model",
      allChannels: "All channels",
      clearFilter: "Clear filter",
      filteredHint: "filtered highlight",
      searchError: "Search error / model...",
      logsHint: "Last 50 request logs",
      requestTrend: "Request trend",
      requestCount: "Requests",
      logDetails: "View details",
      logDetailFailed: "Could not load details",
      retry: "Retry",
      autoRefresh: "Auto refresh",
      autoRefreshOn: "Auto refresh on (every 5s)",
      columns: {
        name: "Name", provider: "Provider / Protocol", baseUrl: "Upstream URL", models: "Models",
        route: "Route", status: "Status", requests: "Requests", actions: "Actions",
        id: "ID", key: "API Key", user: "User", quota: "Quota", used: "Used",
        time: "Time", token: "Key", channel: "Channel", tokens: "Tokens",
        error: "Error", latency: "Latency",
      },
      metrics: ["Requests", "Success", "Failed", "Total Tokens", "Prompt Tokens", "Completion Tokens", "Cost", "Avg Latency"],
      cacheHitRate: "Cache hit rate",
      cacheHitTokens: "Cache hits",
      modelTableTitle: "Per-model breakdown",
      modelTableHint: "Input / output / cache hits by model",
    },
  },
};
